/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package include.Tribbler;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Enum type for returning status of a RPC request made to the
 * the Tribbler server.
 */
public enum TribbleStatus implements org.apache.thrift.TEnum {
  OK(1),
  EEXISTS(2),
  INVALID_USER(3),
  INVALID_SUBSCRIBETO(4),
  NOT_IMPLEMENTED(5);

  private final int value;

  private TribbleStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TribbleStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return OK;
      case 2:
        return EEXISTS;
      case 3:
        return INVALID_USER;
      case 4:
        return INVALID_SUBSCRIBETO;
      case 5:
        return NOT_IMPLEMENTED;
      default:
        return null;
    }
  }
}
