/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package include.Tribbler;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Return type for a RPC call to the Tribbler server request user's tribbles.
 */
public class TribbleResponse implements org.apache.thrift.TBase<TribbleResponse, TribbleResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TribbleResponse");

  private static final org.apache.thrift.protocol.TField TRIBBLES_FIELD_DESC = new org.apache.thrift.protocol.TField("tribbles", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TribbleResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TribbleResponseTupleSchemeFactory());
  }

  public List<Tribble> tribbles; // required
  /**
   * 
   * @see TribbleStatus
   */
  public TribbleStatus status; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRIBBLES((short)1, "tribbles"),
    /**
     * 
     * @see TribbleStatus
     */
    STATUS((short)2, "status");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRIBBLES
          return TRIBBLES;
        case 2: // STATUS
          return STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRIBBLES, new org.apache.thrift.meta_data.FieldMetaData("tribbles", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Tribble.class))));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TribbleStatus.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TribbleResponse.class, metaDataMap);
  }

  public TribbleResponse() {
  }

  public TribbleResponse(
    List<Tribble> tribbles,
    TribbleStatus status)
  {
    this();
    this.tribbles = tribbles;
    this.status = status;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TribbleResponse(TribbleResponse other) {
    if (other.isSetTribbles()) {
      List<Tribble> __this__tribbles = new ArrayList<Tribble>();
      for (Tribble other_element : other.tribbles) {
        __this__tribbles.add(new Tribble(other_element));
      }
      this.tribbles = __this__tribbles;
    }
    if (other.isSetStatus()) {
      this.status = other.status;
    }
  }

  public TribbleResponse deepCopy() {
    return new TribbleResponse(this);
  }

  @Override
  public void clear() {
    this.tribbles = null;
    this.status = null;
  }

  public int getTribblesSize() {
    return (this.tribbles == null) ? 0 : this.tribbles.size();
  }

  public java.util.Iterator<Tribble> getTribblesIterator() {
    return (this.tribbles == null) ? null : this.tribbles.iterator();
  }

  public void addToTribbles(Tribble elem) {
    if (this.tribbles == null) {
      this.tribbles = new ArrayList<Tribble>();
    }
    this.tribbles.add(elem);
  }

  public List<Tribble> getTribbles() {
    return this.tribbles;
  }

  public TribbleResponse setTribbles(List<Tribble> tribbles) {
    this.tribbles = tribbles;
    return this;
  }

  public void unsetTribbles() {
    this.tribbles = null;
  }

  /** Returns true if field tribbles is set (has been assigned a value) and false otherwise */
  public boolean isSetTribbles() {
    return this.tribbles != null;
  }

  public void setTribblesIsSet(boolean value) {
    if (!value) {
      this.tribbles = null;
    }
  }

  /**
   * 
   * @see TribbleStatus
   */
  public TribbleStatus getStatus() {
    return this.status;
  }

  /**
   * 
   * @see TribbleStatus
   */
  public TribbleResponse setStatus(TribbleStatus status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TRIBBLES:
      if (value == null) {
        unsetTribbles();
      } else {
        setTribbles((List<Tribble>)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((TribbleStatus)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TRIBBLES:
      return getTribbles();

    case STATUS:
      return getStatus();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TRIBBLES:
      return isSetTribbles();
    case STATUS:
      return isSetStatus();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TribbleResponse)
      return this.equals((TribbleResponse)that);
    return false;
  }

  public boolean equals(TribbleResponse that) {
    if (that == null)
      return false;

    boolean this_present_tribbles = true && this.isSetTribbles();
    boolean that_present_tribbles = true && that.isSetTribbles();
    if (this_present_tribbles || that_present_tribbles) {
      if (!(this_present_tribbles && that_present_tribbles))
        return false;
      if (!this.tribbles.equals(that.tribbles))
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TribbleResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TribbleResponse typedOther = (TribbleResponse)other;

    lastComparison = Boolean.valueOf(isSetTribbles()).compareTo(typedOther.isSetTribbles());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTribbles()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tribbles, typedOther.tribbles);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(typedOther.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, typedOther.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TribbleResponse(");
    boolean first = true;

    sb.append("tribbles:");
    if (this.tribbles == null) {
      sb.append("null");
    } else {
      sb.append(this.tribbles);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TribbleResponseStandardSchemeFactory implements SchemeFactory {
    public TribbleResponseStandardScheme getScheme() {
      return new TribbleResponseStandardScheme();
    }
  }

  private static class TribbleResponseStandardScheme extends StandardScheme<TribbleResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TribbleResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRIBBLES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.tribbles = new ArrayList<Tribble>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  Tribble _elem2; // required
                  _elem2 = new Tribble();
                  _elem2.read(iprot);
                  struct.tribbles.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setTribblesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = TribbleStatus.findByValue(iprot.readI32());
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TribbleResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tribbles != null) {
        oprot.writeFieldBegin(TRIBBLES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tribbles.size()));
          for (Tribble _iter3 : struct.tribbles)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        oprot.writeI32(struct.status.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TribbleResponseTupleSchemeFactory implements SchemeFactory {
    public TribbleResponseTupleScheme getScheme() {
      return new TribbleResponseTupleScheme();
    }
  }

  private static class TribbleResponseTupleScheme extends TupleScheme<TribbleResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TribbleResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTribbles()) {
        optionals.set(0);
      }
      if (struct.isSetStatus()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTribbles()) {
        {
          oprot.writeI32(struct.tribbles.size());
          for (Tribble _iter4 : struct.tribbles)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TribbleResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tribbles = new ArrayList<Tribble>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            Tribble _elem7; // required
            _elem7 = new Tribble();
            _elem7.read(iprot);
            struct.tribbles.add(_elem7);
          }
        }
        struct.setTribblesIsSet(true);
      }
      if (incoming.get(1)) {
        struct.status = TribbleStatus.findByValue(iprot.readI32());
        struct.setStatusIsSet(true);
      }
    }
  }

}

